export const bookCategories = [
    'Fiction',
    'Non-fiction',
    'Mystery',
    'Thriller',
    'Science Fiction',
    'Fantasy',
    'Horror',
    'Romance',
    'Historical Fiction',
    'Biography',
    'Self-help',
    'Business',
    'Travel',
    'Cooking',
    'Art',
]
